### ISSUE TITLE
Mejorar el ejercicio

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m3-evaluacion-intermedia-carmen-tm#1]
Super buen trabajo @carmen-tm !

Algunas pistas para acabarlo:

- [x] Publica en Github Pages
- [x] Elimina archivos sin usar y sus referencias
- [x] Mueve el título fuera de Pokelist (Mi lista de Pokemons) y ponlo a nivel de página (App)
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Mejora los estilos estilos (un archivo sass o css por componente que solo añade clases para ese componente)
- [x] Limpia e indenta el código
- [x] Elimina el código comentado
- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] En el componente del listado hay que recorrer el array de pokemons que le llega por props y pintar un li y un componente con una tarjeta por cada uno.
- [x] Usa el id de cada pokemon para el key de react cuando mapeas y creas un listado de componentes
- [x] Utiliza el nombre del Pokemon para el Alt de la imagen

Cuando tengas esto puedes:

1. Mover el array de pokemons a otro archivo e importarlo en App.
2. Inicializar el estado de App con el array de pokemons y utilizar este en lugar de la constante pokemon.
3. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del 4. estado de App.
5. Pasar este dato al componente Pokemon por props
6. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by carmen-tm** [comment]
Hi @nasivuela ! Thanks for the feedback!
- I think all the main tasks to finish the exercise suggested are done finally :)
- I have started as well the first of the extra ones but is a work-in-progress still... I will keep working on it bit by bit.
Thanks!

**Comment by nasivuela** [comment]
Super buen trabajo!

![](https://media.giphy.com/media/l3q2Z6S6n38zjPswo/giphy.gif)
